import { useRouter } from "next/router";
import Head from "next/head";
import { useEffect, useState } from "react";

export default function Home() {
  const router = useRouter();
  const [isContentVisible, setIsContentVisible] = useState(false);
  // checking if first time user, by checking availability of stored username
  useEffect(() => {
    if (localStorage.getItem("summerx_username")) {
      setIsContentVisible(true);
    } else {
      router.push("/home");
    }
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {isContentVisible ? (
          <p className="text-primary text-center text-3xl">Hello India!</p>
          ) : (
          <></>
        )}
      </main>
    </>
  );
}
