import { useRouter } from "next/router";
import Head from "next/head";
import { useEffect, useState } from "react";
import Header from "../components/Header";

export default function Home() {
  const router = useRouter();
  const [isContentVisible, setIsContentVisible] = useState(false);
  // checking if first time user, by checking availability of stored username
  useEffect(() => {
    if (localStorage.getItem("summerx_username")) {
      setIsContentVisible(true);
    } else {
      router.push("/home");
    }
  });
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="p-6 text-primary dark:text-secondary transition-all ease-in-out">
        {isContentVisible ? (
          <>
            <Header />
          </>
        ) : (
          <></>
        )}
      </main>
    </>
  );
}
